### ISSUE TITLE
API for String and ByteString

### ISSUE THREAD

**Issue by maoe** [peti/hsyslog#16]
The API of this library has changed quite a bit since v1.x and I found the current API isn't as convenient to use as it used to be because of the use of `CStringLen`. Is this library supposed to be just a thin wrapper around `syslog(3)` and not to be used directly from applications anymore?

If it's not the case, I'd like to propose to add two modules:

* `System.Posix.Syslog.String` which exposes `syslog :: Maybe Facility -> Priority -> String -> IO ()` with other common functions and data types
* and `System.Posix.Syslog.ByteString` which exposes `syslog :: Maybe Facility -> Priority -> ByteString -> IO ()` with other common functions and data types.

The idea here is that we provide a slightly higher level `syslog` function with other string-agnostic functions/types so that users can use the whole API without resorting to low-level functions like `withCStringLen` or `unsafeUseAsCStringLen`. This doesn't need to introduce extra dependencies. Also we can keep the `System.Posix.Syslog` module as-is as a thin wrapper around `syslog(3)`.

What do you think? If it sounds good I'll make a pull request.

**Comment by maoe** [comment]
Or we could just add `syslogString` and `syslogByteString` if we don't mind the ugly names.

**Comment by peti** [comment]
See https://github.com/peti/hsyslog/blob/master/example/Main.hs#L12-L24 for an example of how to log `ByteString` (or any type) with `syslog` conveniently. Accepting `CStringLen` is actually  very flexible, because may other types are, essentially, that type. This allows us to log messages without copying them, something previous versions of the API required.

**Comment by maoe** [comment]
I'm aware that I can use `withCStringLen` or `unsafeUseAsCStringLen` to work with `String` or `ByteString` and I have no doubts about using `CStringLen` as the most basic building block. But still I'd argue it's a bit inconvenient for application writers to have to import a module and define a wrapper to use `syscall` at every application.

I don't think we need something like the `LogMessage` class in the library as I suppose it's unlikely to use multiple string types for logging in an application. Hence I proposed the additional modules with the same functions name.

**Comment by peti** [comment]
Personally, I feel that a `LogMessage` class is *precisely* the way an advanced API should be defined. The Haskell community has adopted this habit of using the module system to define a common API for several distinct but similar types (like `containers` and `bytestring` do), but this is just crazy in my humble opinion. It leads to name clashes, code duplication, and excessive boilerplate code all over the place. I'd rather not go down that road. Suppose that a user wants to log messages represented as `String` and `ByteString`. In that case, she'd already have to import 2 modules instead of just one. Now you add `Text` into the mix, and then we're at 3 modules that need to be imported -- with all 3 of them defining the same names. IMHO, a class for things that can be represented as a memory buffer is a far superior solution. There are many libraries that use this approach, like http://hackage.haskell.org/package/logging-facade, which also has a syslog back-end. Then there is the package http://hackage.haskell.org/package/memory, which abstracts the notion of a "memory array" and which could be used. Last but not least, in my `hopenssl` library I defined my own class, http://hackage.haskell.org/package/hopenssl-2.2/docs/OpenSSL-Digest.html#t:Digestable, so that I could provide a convenient-to-use polymorphic `digest` function. If I'd go for generalizing `syslog`, then this would be the path I'd want to explore.

**Comment by peti** [comment]
Can this issue be closed?

**Comment by maoe** [comment]
Sorry, I got distracted.

Overall, I understand you prefer the classy interface and although I still prefer separate modules, I'm happy with the classy one compared to the current interface.

> Personally, I feel that a LogMessage class is precisely the way an advanced API should be defined.
> [snip]
> Suppose that a user wants to log messages represented as String and ByteString.

I thought `LogMessage` was unnecessary because I'd say this assumption of using multiple string types in an application rarely holds in practice.

> It leads to name clashes, code duplication, and excessive boilerplate code all over the place.

As I said above, I don't think name claches are a problem in practice.

In this particular case, I think code duplication should be minimal. There would be two `syslog` functions that only differ how to convert a string type into `CStringLen`.

Boilerplate code is certainly a downside. We need module declarations, export lists, import lists for each module. I don't think it's _excessive_ though.

> There are many libraries that use this approach, like http://hackage.haskell.org/package/logging-facade, which also has a syslog back-end.

This package looks nice. I don't get how it relates to the classy interface though. It uses only the `String` type for messages.

> If I'd go for generalizing syslog, then this would be the path I'd want to explore.

I see.

**Comment by peti** [comment]
> I thought LogMessage was unnecessary because I'd say this assumption of using multiple string types in an application rarely holds in practice.

I don't know. I haven't made any effort to gather empiric evidence about how people use logging libraries, so I can't say anything about that topic. All I can say that *I*, personally, find myself having to deal with multiple representations of text quite frequently. Anyhow, I believe that a class-based abstraction is a superior design, in general, even if you're using it to handle only a single type of text.

> [logging-facade] looks nice. I don't get how it relates to the classy interface though. It uses only the String type for messages.

You are right! Not sure why I thought it implemented a different API. Apparently, I confused it with something else, but now I don't quite remember which library I was thinking of.
